### ISSUE TITLE
Flooded with skills after picking position type

### ISSUE THREAD

**Issue by mpmenne** [Launch-Code/skills-widget#1]
After selecting position type, I see all of the skills for a position type (even though I haven't selected a core competency).

This should only show the skills specific to a particular position type.  For example, frond-end developer will always need to see HTML, CSS, LESS, etc.

![screen shot 2016-03-16 at 12 18 24 pm](https://cloud.githubusercontent.com/assets/217904/13822097/6a651f76-eb72-11e5-87a7-e119e76d441b.png)

Because we show all of the skills at once, you really don't see any impact when you select a core competency:
![screen shot 2016-03-16 at 12 33 17 pm](https://cloud.githubusercontent.com/assets/217904/13822355/4a703420-eb73-11e5-97ee-9dd8be21c9f2.png)
(I clicked Java)
![screen shot 2016-03-16 at 12 21 25 pm](https://cloud.githubusercontent.com/assets/217904/13822323/2e29e090-eb73-11e5-98fd-6b1d56a1bed0.png)

**Comment by eliotpiering** [comment]
Thanks, for the feedback Mike.  This was helpful when fixing this issue.  It should be fixed now
